version: '3'

services:
  docmost:
    # 使用自定义构建的镜像（隐藏了分享页面导航栏）
    image: docmost-custom:latest
    # 如果需要从源码构建，可以取消注释下面的 build 配置
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'c1905985497168325b59bc6f2a4459f61ed9d4acb54c80439d92d4a0e32fc4ba'
      DATABASE_URL: 'postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3200:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data: